"""empty message

Revision ID: 08db2d27df57
Revises: 82488cfe7b56
Create Date: 2019-07-29 13:37:49.895610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db2d27df57'
down_revision = '82488cfe7b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet')
    op.drop_table('recipe_diet')
    op.add_column('recipe', sa.Column('requirement', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'requirement')
    op.create_table('recipe_diet',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['recipe.id'], name='recipe_diet_diet_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['diet.id'], name='recipe_diet_recipe_id_fkey')
    )
    op.create_table('diet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='diet_pkey')
    )
    # ### end Alembic commands ###
