"""empty message

Revision ID: b19052c9433c
Revises: 42b8da337a43
Create Date: 2019-07-29 14:13:56.249631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19052c9433c'
down_revision = '42b8da337a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet')
    op.drop_table('recipe_diet')
    op.add_column('recipe', sa.Column('requirement', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'requirement')
    op.create_table('recipe_diet',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['recipe.id'], name='recipe_diet_diet_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['diet.id'], name='recipe_diet_recipe_id_fkey')
    )
    op.create_table('diet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='diet_pkey')
    )
    # ### end Alembic commands ###
